routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Website\BarangController@index')->name('index');
Route::group(['as' => 'barang.', 'prefix' => '/barang'], function () {
  Route::get('/', 'Website\BarangController@index')->name('index');
  Route::get('/create', 'Website\BarangController@create')->name('create');
  Route::post('/store', 'Website\BarangController@store')->name('created');
  Route::get('/show/{id}', 'Website\BarangController@show')->name('show');
  Route::get('/edit/{id}', 'Website\BarangController@edit')->name('edit');
  Route::post('/update/{id}', 'Website\BarangController@update')->name('update');
  Route::post('/destroy/{id}', 'Website\BarangController@destroy')->name('destroy');

  Route::group(['as' => 'stok.', 'prefix' => '/stok'], function () {
    Route::get('/{id}/create', 'Website\StokController@create')->name('create');
    Route::post('/{id}store', 'Website\StokController@store')->name('created');
    Route::get('/edit/{id}', 'Website\StokController@edit')->name('edit');
    Route::post('/update/{id}', 'Website\StokController@update')->name('update');
    Route::post('/destroy/{id}', 'Website\StokController@destroy')->name('destroy');
  });
});

Route::group(['as' => 'transaksi.', 'prefix' => '/transaksi'], function () {
  Route::get('/', 'Website\TransaksiController@index')->name('index');
  Route::get('/create', 'Website\TransaksiController@create')->name('create');
  Route::post('/store', 'Website\TransaksiController@store')->name('created');
  Route::get('/show/{id}', 'Website\TransaksiController@show')->name('show');
  Route::get('/edit/{id}', 'Website\TransaksiController@edit')->name('edit');
  Route::post('/update/{id}', 'Website\TransaksiController@update')->name('update');
  Route::post('/destroy/{id}', 'Website\TransaksiController@destroy')->name('destroy');
});

app/Http/Controllers/Website/BarangController.php
<?php

namespace App\Http\Controllers\Website;

use App\Entities\Barang;
use App\Entities\Stok;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\Responder;
use App\Helper\UploadImage;
use Validator;

class BarangController extends Controller
{
  use Responder;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['barangs'] = Barang::all();
        $data['stoks'] = Stok::all();

        return view('website.barang.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['type'] = "create";
        return view('website.barang.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
          'image' => 'required',
          'nama_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $barang = new Barang();
          $barang->kode_barang = generate_unique_string_and_int(4,4);
          $barang->nama_barang = $request->nama_barang;
          if (!empty($request->file('image'))) {
              $barang->gambar_barang = UploadImage::single($request->image, 'random', Barang::$directory_image);
          }

          if ($barang->save()) {
            $response['redirect_url'] = route('index');
            return $this->response(200, $response);
          }
        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $data['data'] = Barang::find($id);
      return view('website.barang.detail',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['type'] = "edit";
        $data['data'] = Barang::find($id);
        return view('website.barang.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
          'nama_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $barang = Barang::find($id);
          $barang->nama_barang = $request->nama_barang;
          if (!empty($request->file('image'))) {
            if (is_file_exists($barang->gambar_barang)) {
                remove_file($barang->gambar_barang);
            }
            $barang->gambar_barang = UploadImage::single($request->image, 'random', Barang::$directory_image);
          }

          if ($barang->save()) {
            $response['redirect_url'] = route('index');
            return $this->response(200, $response);
          }
        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $barang = Barang::find($id);

        if ($barang->stok->count() == 0) {
          if (is_file_exists($barang->gambar_barang)) {
              remove_file($barang->gambar_barang);
          }
          $barang->delete();
          $response['redirect_url'] = route('index');
          return $this->response(200, $response);
        }else{
          $response['message'] = array_merge(['Barang mempunyai stok']);
          return $this->response(400, $response);
        }
    }
}

app/Http/Controllers/Website/StokController.php
<?php

namespace App\Http\Controllers\Website;

use App\Entities\Stok;
use App\Entities\Barang;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\Responder;
use Validator;

class StokController extends Controller
{
  use Responder;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $data['type'] = "create";
        $data['data'] = Barang::find($id);
        return view('website.stok.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id)
    {
        $validator = Validator::make($request->all(), [
          'total_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $stok = new Stok();
          $stok->total_barang = $request->total_barang;
          $stok->jenis_stok = $request->jenis_stok;
          $stok->id_barang = $id;

          if ($stok->save()) {
            $response['redirect_url'] = route('index');
            return $this->response(200, $response);
          }
        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['type'] = "edit";
        $data['dataStok'] = Stok::find($id);
        $data['data'] = $data['dataStok']->barang;
        return view('website.stok.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
          'total_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $stok = Stok::find($id);
          $stok->total_barang = $request->total_barang;
          $stok->jenis_stok = $request->jenis_stok;

          if ($stok->save()) {
            $response['redirect_url'] = route('index');
            return $this->response(200, $response);
          }
        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $stok = Stok::find($id);

        $stok->delete();
        $response['redirect_url'] = route('index');
        return $this->response(200, $response);
    }
}

app/Http/Controllers/Website/TransaksiController.php
<?php

namespace App\Http\Controllers\Website;

use App\Entities\Transaksi;
use App\Entities\Stok;
use App\Entities\Barang;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\Responder;
use Validator;

class TransaksiController extends Controller
{
  use Responder;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['transaksis'] = Transaksi::all();

        return view('website.transaksi.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['type'] = "create";
        $data['barangs'] = Barang::all();
        return view('website.transaksi.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
          'total_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $transaksi = new Transaksi();

          $stokIn = Stok::where('id_barang',$request->id_barang)->where('jenis_stok','in')->get()->sum('total_barang');
          $stokOut = Stok::where('id_barang',$request->id_barang)->where('jenis_stok','out')->get()->sum('total_barang');
          $jumlahTransaksiPembelian = Transaksi::where('id_barang',$request->id_barang)->where('jenis_transaksi','pembelian')->get()->sum('total_barang');
          $jumlahTransaksiPenjualan = Transaksi::where('id_barang',$request->id_barang)->where('jenis_transaksi','penjualan')->get()->sum('total_barang');
          $realStok = ($stokIn + $jumlahTransaksiPembelian) - ($jumlahTransaksiPenjualan + $stokOut);
          if ($request->total_barang > $realStok && $request->jenis_transaksi != "pembelian") {
            $response['message'] = array_merge(['Jumlah barang melebihi stok'],['stok saat ini '.$realStok]);
            return $this->response(400, $response);
          }else{
            $transaksi->kode_transaksi = generate_unique_string_and_int(5,5);
            $transaksi->id_barang = $request->id_barang;
            $transaksi->total_barang = $request->total_barang;
            $transaksi->jenis_transaksi = $request->jenis_transaksi;

            if ($transaksi->save()) {
              $response['redirect_url'] = route('transaksi.index');
              return $this->response(200, $response);
            }
          }

        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $data['data'] = Transaksi::find($id);
      return view('website.transaksi.detail',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['type'] = "edit";
        $data['data'] = Transaksi::find($id);
        $data['barangs'] = Barang::all();
        return view('website.transaksi.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
          'total_barang' => 'required',
        ]);

        if ($validator->passes()) {
          $transaksi = Transaksi::find($id);
          $stokIn = Stok::where('id_barang',$request->id_barang)->where('jenis_stok','in')->get()->sum('total_barang');
          $stokOut = Stok::where('id_barang',$request->id_barang)->where('jenis_stok','out')->get()->sum('total_barang');
          $jumlahTransaksiPembelian = Transaksi::where('id_barang',$request->id_barang)->where('jenis_transaksi','pembelian')->get()->sum('total_barang');
          $jumlahTransaksiPenjualan = Transaksi::where('id_barang',$request->id_barang)->where('jenis_transaksi','penjualan')->get()->sum('total_barang');
          $realStok = ($stokIn + $jumlahTransaksiPembelian) - ($jumlahTransaksiPenjualan + $stokOut);
          if ($request->total_barang > $realStok && $request->jenis_transaksi != "pembelian") {
            $response['message'] = array_merge(['Jumlah barang melebihi stok'],['stok saat ini '.$realStok]);
            return $this->response(400, $response);
          }else{
            $transaksi->total_barang = $request->total_barang;
            $transaksi->jenis_transaksi = $request->jenis_transaksi;
            if ($transaksi->save()) {
              $response['redirect_url'] = route('transaksi.index');
              return $this->response(200, $response);
            }
          }


        }else{
          $response['message'] = array_merge(['Data Invalid!'], $validator->errors()->all());
          return $this->response(400, $response);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $transaksi = Transaksi::find($id);
        $transaksi->delete();
        $response['redirect_url'] = route('transaksi.index');
        return $this->response(200, $response);

    }
}

resources/views/website/barang/detail.blade.php
@extends('website.template')
@section('content')
<div class="content-wrapper">
  <div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
      <div class="page-title d-flex">
        <h4> <span class="font-weight-semibold">Detail Barang</span></h4>
      </div>
    </div>
  </div>
  <div class="content">
      <div class="card">
				<div class="card-header header-elements-inline">
					<h5 class="card-title"><b>Form Barang</b></h5>
				</div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <img src="{{asset($data->gambar_barang)}}" class="width-100-percent"  alt="">
            </div>
            <div class="col-md-8">
              <h3><b>Kode Barang</b></h3>
              <p class="f-s15">{{$data->kode_barang}}</p>
              <h3><b>Nama Barang</b></h3>
              <p class="f-s15">{{$data->nama_barang}}</p>
            </div>
          </div>
          <a href="{{route('index')}}"><button type="button" class="btn btn-success float-right"><i class="icon-arrow-left7 mr-2"></i> BACK</button></a>
        </div>
			</div>
  </div>
</div>
@endsection
@section('scripts')
@endsection

resources/views/website/barang/form.blade.php
@extends('website.template')
@section('styles')
  <link href="{{ asset('global_assets/assets/plugins/fileuploads/css/dropify.min.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="content-wrapper">
  <div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
      <div class="page-title d-flex">
        <h4> <span class="font-weight-semibold">{{$type == 'create' ? "Tambah" : "Edit"}} Barang</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
      </div>
    </div>
  </div>
  <div class="content">
      <div class="card">
				<div class="card-header header-elements-inline">
					<h5 class="card-title"><b>Form Barang</b></h5>
				</div>
        <div class="card-body">
          <form class="kt-form" id="form-submit" data-action="{{($type == 'create') ? route('barang.created') : route('barang.update',$data->id)}}" enctype="multipart/form-data" autocomplete="off">
            {{csrf_field()}}
            <div class="form-group">
                <label>Gambar Barang</label>
                <input type="file" class="dropify" name="image" data-height="300" data-default-file="{{$type == 'create' ? '' : asset($data->gambar_barang)}}" />
            </div>
            <div class="form-group row">
              <label class="col-form-label col-lg-12">Nama Barang</label>
              <div class="col-lg-12">
                <input type="text" name="nama_barang" placeholder="masukan nama barang" value="{{$type == 'create' ? '' : $data->nama_barang}}" class="form-control">
              </div>
            </div>
            <button type="submit" class="btn btn-success float-right"><i class="icon-paperplane mr-2"></i> {{$type == 'create' ? "BUAT" : "SIMPAN"}}</button>
          </form>
        </div>
			</div>
  </div>
</div>
@endsection
@section('scripts')
<script src="{{ asset('global_assets/js/form/form-submit.js') }}"></script>
<script src="{{asset('global_assets/js/plugins/buttons/spin.min.js')}}"></script>
<script src="{{asset('global_assets/js/plugins/buttons/ladda.min.js')}}"></script>
<script src="{{asset('global_assets/js/demo_pages/components_buttons.js')}}"></script>
<script src="{{ asset('global_assets/assets/plugins/fileuploads/js/dropify.min.js') }}"></script>
<script type="text/javascript">
  $('.dropify').dropify({
      messages: {
          'default': 'Drag and drop a file here or click',
          'replace': 'Drag and drop or click to replace',
          'remove': 'Remove',
          'error': 'Ooops, something wrong appended.'
      },
      error: {
          'fileSize': 'The file size is too big (1M max).'
      }
  });
</script>
@endsection

resources/views/website/barang/index.blade.php
@extends('website.template')
@section('content')
<div class="content-wrapper">
  <div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
      <div class="page-title d-flex">
        <h4> <span class="font-weight-semibold">Barang</span></h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
      </div>
    </div>
  </div>
  <div class="content">
      <div class="card">
				<div class="card-header header-elements-inline">
					<h5 class="card-title">Daftar Barang</h5>
          <a href="{{route('barang.create')}}"><button type="button" class="btn btn-light"><i class="icon-plus3 mr-2"></i> Tambah Barang</button></a>
				</div>
				<table class="table datatable-barang">
					<thead>
						<tr>
							<th>No</th>
              <th>ID Barang</th>
							<th>Kode Barang</th>
							<th>Nama Barang</th>
              <th class="width-10-percent">Stok</th>
							<th class="width-25-percent">Aksi</th>
						</tr>
					</thead>
					<tbody>
            <?php foreach ($barangs as $key => $barang): ?>
						<tr>
              <td>{{$key+1}}</td>
              <td>{{$barang->id}}</td>
							<td>{{$barang->kode_barang}}</td>
              <td><a href="{{route('barang.show',$barang->id)}}">{{$barang->nama_barang}}</a></td>
              <?php
              $stokIn = App\Entities\Stok::where('id_barang',$barang->id)->where('jenis_stok','in')->get()->sum('total_barang');
              $stokOut = App\Entities\Stok::where('id_barang',$barang->id)->where('jenis_stok','out')->get()->sum('total_barang');
              $jumlahTransaksiPembelian = App\Entities\Transaksi::where('id_barang',$barang->id)->where('jenis_transaksi','pembelian')->get()->sum('total_barang');
              $jumlahTransaksiPenjualan = App\Entities\Transaksi::where('id_barang',$barang->id)->where('jenis_transaksi','penjualan')->get()->sum('total_barang');
              $realStok = ($stokIn + $jumlahTransaksiPembelian) - ($jumlahTransaksiPenjualan + $stokOut);
               ?>
              <td>{{$realStok}}</td>
							<td>
                <a href="{{route('barang.stok.create',$barang->id)}}"><button type="button" class="btn btn-light"><i class="icon-plus3 mr-2"></i> Tambah stok</button></a>
                <a href="{{route('barang.edit',$barang->id)}}"><button type="button" class="btn btn-info"><i class="icon-pencil3 mr-2"></i> Edit</button></a>
                <button type="button" onclick="deleteIt(this)" data-action="{{route('barang.destroy',$barang->id)}}" class="btn btn-danger"><i class="icon-trash-alt mr-2"></i> Hapus</button>
              </td>
						</tr>
            <?php endforeach; ?>
					</tbody>
				</table>
			</div>

      <div class="card">
				<div class="card-header header-elements-inline">
					<h5 class="card-title">Daftar Stok</h5>
				</div>
				<table class="table datatable-barang">
					<thead>
						<tr>
							<th>No</th>
              <th>Nama Barang</th>
							<th>Type</th>
              <th class="width-10-percent">Stok</th>
							<th class="width-25-percent">Aksi</th>
						</tr>
					</thead>
					<tbody>
            <?php foreach ($stoks as $key => $stok): ?>
						<tr>
              <td>{{$key+1}}</td>
							<td>{{$stok->barang->nama_barang}}</td>
              <?php if ($stok->jenis_stok == "in"): ?>
                <td><span class="badge bg-success ml-md-3 mr-md-auto">In</span></td>
              <?php else: ?>
                <td><span class="badge bg-danger ml-md-3 mr-md-auto">Out</span></td>
              <?php endif; ?>
              <td>{{$stok->total_barang}}</td>
							<td>
                <a href="{{route('barang.stok.edit',$stok->id)}}"><button type="button" class="btn btn-info"><i class="icon-pencil3 mr-2"></i> Edit</button></a>
                <button type="button" onclick="deleteIt(this)" data-action="{{route('barang.stok.destroy',$stok->id)}}" class="btn btn-danger"><i class="icon-trash-alt mr-2"></i> Hapus</button>
              </td>
						</tr>
            <?php endforeach; ?>
					</tbody>
				</table>
			</div>
  </div>
</div>
@endsection
@section('scripts')
<script src="{{asset('global_assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
<script src="{{asset('global_assets/js/demo_pages/datatables_basic.js')}}"></script>
<script src="{{asset('global_assets/js/plugins/forms/selects/select2.min.js')}}"></script>
<script src="{{asset('global_assets/js/plugins/buttons/spin.min.js')}}"></script>
<script src="{{asset('global_assets/js/plugins/buttons/ladda.min.js')}}"></script>
<script src="{{asset('global_assets/js/demo_pages/components_buttons.js')}}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@endsection